dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - set -e
  - mkdir -p build && cd build
  - cmake "${TRAVIS_BUILD_DIR}"
  - make -j4
  - cd ${TRAVIS_BUILD_DIR}/build/lightex
  - ./tester
  - PYTHONPATH=. python3 "${TRAVIS_BUILD_DIR}/lightex/tests/canon/run.py"
  - cd ${TRAVIS_BUILD_DIR}/build/lightex2
  - ./tester2
